BookReview/urls.py
from django.conf.urls import url, include


urlpatterns = [
    url(r'^books/', include('apps.book_review.urls', namespace='book_review')),
    url(r'^', include('apps.login_reg.urls', namespace='login_reg')),
]

apps/login_reg/urls.py
from django.conf.urls import url
from . import views

app_name='login_reg'
urlpatterns = [
    #home route- displays registration and login forms
    url(r'^$', views.index, name='index'),

    #process registration form
    #sends to books_app index on success
    url(r'^register$', views.register, name='register'),

    #process login form
    #sends to books_app index on success
    url(r'^login$', views.login, name='login'),

    #display form for updating user info and security questions
    url(r'^account$', views.account, name='account'),

    url(r'^show/(?P<id>[\d]{1,})$', views.show, name='show'),
    #process update form
    #sends to success on success
    url(r'^update$', views.update, name='update'),

    #Logs user out
    #Sends to index
    url(r'^delete/(?P<delete_id>[\d]{1,})$', views.delete, name='delete'),

    #Logs user out
    #Sends to index
    url(r'^logout$', views.logout, name='logout'),
]

apps/login_reg/models.py
from __future__ import unicode_literals
from django.db import models
import re, time
import bcrypt

#regex object stores regex validations and error messages
#some regexs are duplicates so that field-names can be preserved,
#fields like email and login_email have idetical regex but errors need to be displayed in different places
regex = {
    'first_name' : (re.compile(r'^[a-zA-Z]{2,}$'), "Name must be at least two letter long with no numbers"),
    'last_name' : (re.compile(r'^[a-zA-Z]{2,}$'), "Name must be at least two letter long with no numbers"),
    'email' : (re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$'), "Please enter a valid email"),
    'login_email' : (re.compile(r'^[a-zA-Z0-9\.\+_-]+@[a-zA-Z0-9\._-]+\.[a-zA-Z]*$'), "Please enter a valid email"),
    'birthday' : (re.compile(r'^[0-9]{4}-[0-9]{2}-[0-9]{2}$'), "Please enter a valid date"),
    'password' : (re.compile(r'(?=.*[A-Z])(?=.*[0-9])[a-zA-Z0-9]{8,}'), "Please enter a valid password"),
    'login_password' : (re.compile(r'(?=.*[A-Z])(?=.*[0-9])[a-zA-Z0-9]{8,}'), "Please enter a valid password"),
}

class UserManager(models.Manager):
    #Checks for empty fields and Uses regex object to validate format.
    #first value in tuple is true or false- registration is valid
    #second value returns an error notes object if form has errors, or a user info object if form is valid
    def validateFields(self, form_data):
        print "Starting login_reg.models.py UserManager validateFields method"
        valid = True
        error_notes = {}
        #Check for empty fields
        for key, value in form_data.items():
            print "Checking for value in {} field".format(key)
            if len(value) == 0:
                print "//////////////////// Form Error- {} field is empty".format(key)
                valid = False
                error_notes[key] = "This field cannot be empty"

        #Check for valid field formats- if regex exists for field- validate
        for key, value in form_data.items():
            #Check to see if regex exists for field
            if key in regex:
                print "Checking format of {} field".format(key)
                if not regex[key][0].search(value):
                    print "//////////////////// Form Error- {} field is invalid format".format(key)
                    valid = False
                    #If invalid, and no error note has been set for this field- pull error matching error message from regex dictionary
                    #The error notes will contain the most basic note for each field.
                    if not key in error_notes:
                        error_notes[key] = regex[key][1]

        if 'birthday' in form_data:
            #Check that user birthday at least 14 years before current date
            if not User.objects.checkAge(form_data['birthday']):
                valid = False
                if not 'birthday' in error_notes:
                    error_notes['birthday'] = "You must be at least 14 years old to register an account"

        return (valid, error_notes)

    def checkAge(self, birthday):
        print "Starting login_reg.models.py UserManager checkAge method"
        #Check that user birthday at least 14 years before current date
        #age-restriction is calculated by getting seconds since epoch, subtrating seconds per year * minimum age in years and formatting to string-time
        age_restriction = time.strftime("%Y-%m-%d", time.localtime(time.time() - (31561600 * 14)))
        birthday = str(birthday)
        print "age_restriction", age_restriction
        print "birthday", birthday
        print "birthday <= age_restriction is:", birthday <= age_restriction
        if birthday <= age_restriction:
            return True
        else:
            return False

    def register(self, form_data):
        print "Starting login_reg.models.py UserManager register method"
        #Uses validateFields method to check for basic field validations- if successful,
        #checks to make sure new email is not already in DB and creates new user.
        response = User.objects.validateFields(form_data)
        valid = True
        error_notes = response[1]
        #Check if basic validation returned false
        if not response[0]:
            return (False, error_notes)
        #check that confirm-password matches password
        if form_data['password'] != form_data['c_password']:
            valid = False
            error_notes['c_password'] = "confirm-password does not match password"
        #Check to make sure email does not exist in DB- save this for last because it requires DB call
        try:
            email_check = User.objects.get(email=form_data['email'])
            print "Email already exists in DB"
            valid = False
            error_notes['email'] = "The email you entered is already registered to a different account. Please use a different email or login below"
        except User.DoesNotExist:
            print "Email is not duplicate"

        if valid == False:
            print "Form has errors"
            return (False, error_notes)

        #Create user object in DB
        print "//////////////////////////////////Form is Vald- Creating new User"
        password = bcrypt.hashpw(form_data['password'].encode(encoding="utf-8", errors="strict"), bcrypt.gensalt())
        new_user = User.objects.create(first_name=form_data['first_name'], last_name=form_data['last_name'], email=form_data['email'], birthday=form_data['birthday'], password=password)
        new_user.save()
        print new_user.id
        return (True, new_user.id)

    def login(self, form_data):
        print "Starting login_reg.models.py UserManager login method"
        #Uses validateFields method to check for basic field validations- if successful,
        #checks to make sure email is in DB and that password matches password in DB.
        response = User.objects.validateFields(form_data)
        valid = True
        error_notes = response[1]
        #Check if basic validation returned false
        if not response[0]:
            return (False, error_notes)
        #check that an account exists for the email
        try:
            user = User.objects.get(email=form_data['login_email'])
            print "Email found in DB"

        except User.DoesNotExist:
            valid = False
            print "Login email not found in DB"
            error_notes['login_email'] = "The password/email combination you entered does not match"

        #Check that the password matches the password in the DB
        password = form_data['login_password'].encode(encoding="utf-8", errors="strict")
        hashed_password = user.password.encode(encoding="utf-8", errors="strict")
        if bcrypt.hashpw(password, hashed_password) == hashed_password:
            print "Login Successful!"
            return (True, user.id)
        else:
            print "Password does not match record"
            error_notes['login_email'] = "The password/email combination you entered does not match"
            return (False, error_notes)

    def update(self, form_data, login_id):
        print "Starting login_reg.models.py UserManager update method"
        #Uses validateFields method to check for basic field validations- if successful,
        #checks to make sure new email is not already registered to a different account
        #Updates User info if form is valid
        response = User.objects.validateFields(form_data)
        valid = True
        error_notes = response[1]
        #Check if basic validation returned false
        if not response[0]:
            return (False, error_notes)

        #Check to make sure email does not belong to a different account in the DB- save this for last because it requires DB call
        try:
            email_check = User.objects.get(email=form_data['email'])
            if email_check.id != login_id:
                print "Email is already registered to another account"
                valid = False
                error_notes['email'] = "The email you entered is already registered to a different account"
        except User.DoesNotExist:
            print "Email is not duplicate or belongs to user"

        if valid == False:
            print "Form has errors"
            return (False, error_notes)

        print "//////////////////////////////////Form is Vald- Updating User"
        user = User.objects.get(id=login_id)
        user.first_name = form_data['first_name']
        user.last_name = form_data['last_name']
        user.email = form_data['email']
        user.birthday = form_data['birthday']
        user.save()
        return (True, True)

class User(models.Model):
    first_name = models.CharField(max_length=55)
    last_name = models.CharField(max_length=55)
    email = models.CharField(max_length=55)
    birthday = models.DateField()
    password = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = UserManager()

apps/login_reg/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from models import User

def index(request):
    print "/////////////////////////// Starting login_reg.views.py index route"


    return render(request, 'login_reg/index.html')

def register(request):
    print "/////////////////////////// Starting login_reg.views.py register route"
    if request.method == 'POST':
        form = request.POST
        form_data = {
            'first_name' : form['first_name'],
            'last_name' : form['last_name'],
            'email' : form['email'],
            'birthday' : form['birthday'],
            'password' : form['password'],
            'c_password' : form['c_password'],
        }
        response = User.objects.register(form_data)
        #response[0] is True or False- Registration was successful
        #response[1] is object containing new user-id on success- object containing error-notes on failure
        print response[0], response[1]
        if response[0]:
            print "Registration was successful"
            request.session['login_id'] = response[1]
            return redirect(reverse('book_review:index'))

        else:
            print "Registration has errors"
            #Load error_notes returned from registration method into messages
            error_notes = response[1]
            for key, note in error_notes.items():
                messages.error(request, note, extra_tags=key)

            #Preserve any values that do not have error messages and pass them back to the registration form
            for key, value in form_data.items():
                if key not in error_notes:
                    messages.info(request, value, extra_tags=key + "_value")

            return redirect('/')

    else:
        #If the route recieves a non-POST request- assume something shady is going on- log the user out
        #this might be a little harsh if there are legitimate ways a user might accidentally send a GET request to /register
        print "Invalid request method"
        return redirect('/logout')

def login(request):
    print "/////////////////////////// Starting login_reg.views.py login route"
    if request.method == 'POST':
        form = request.POST
        form_data = {
            'login_email' : form['login_email'],
            'login_password' : form['login_password'],
        }
        response = User.objects.login(form_data)
        #response[0] is True or False- Registration was successful
        #response[1] is object containing user information on success- object containing error notes on failure
        print response[0], response[1]
        if response[0]:
            print "Login was successful"
            request.session['login_id'] = response[1]
            return redirect(reverse('book_review:index'))

        else:
            print "Login has errors"
            #Load error_notes returned from registration method into messages
            error_notes = response[1]
            for key, note in error_notes.items():
                messages.error(request, note, extra_tags=key)

            return redirect('/')
    else:
        print "Invalid request method"
        return redirect('/logout')

def success(request):
    print "/////////////////////////// Starting login_reg.views.py success route"
    # Check to make sure user is logged in
    try:
        request.session['login_id']
    except KeyError:
        print "User is not logged in"
        return redirect('/')

    users = User.objects.all()
    context = {
        'users' : users,
    }
    return redirect(reverse('book_review:index'))
    #return render(request, 'login_reg/success.html', context)

def account(request):
    print "/////////////////////////// Starting login_reg.views.py account route"
    # Check to make sure user is logged in
    try:
        request.session['login_id']
    except KeyError:
        print "User is not logged in"
        return redirect('/')

    try:
        login_user = User.objects.get(id=request.session['login_id'])
    #This should never run, but it will prevent the server from breaking if the user is
    #somehow logged in with a bad id
    except User.DoesNotExist:
        print "User matching id not found in records"
        return redirect('/logout')

    request.session['user_info'] = {
        'first_name' : login_user.first_name,
        'last_name' : login_user.last_name,
        'email' : login_user.email,
        'birthday' : login_user.birthday.isoformat(),
    }

    return render(request, 'login_reg/account.html')

def show(request, id):
    print "/////////////////////////// Starting login_reg.views.py show route"
    # Check to make sure user is logged in
    try:
        request.session['login_id']
    except KeyError:
        print "User is not logged in"
        return redirect('/')

    try:
        user = User.objects.get(id=id)
    except User.DoesNotExist:
        print "User matching id not found in records"
        return redirect(reverse('book_review:index'))

    request.session['user_info'] = {
        'first_name' : login_user.first_name,
        'last_name' : login_user.last_name,
        'email' : login_user.email,
        'birthday' : login_user.birthday.isoformat(),
    }

    return render(request, 'login_reg/show.html')

def update(request):
        print "/////////////////////////// Starting login_reg.views.py update route"
        if request.method == 'POST':
            form = request.POST
            form_data = {
                'first_name' : form['first_name'],
                'last_name' : form['last_name'],
                'email' : form['email'],
                'birthday' : form['birthday'],
            }
            response = User.objects.update(form_data, request.session['login_id'])
            #response[0] is True or False- Registration was successful
            #response[1] is True on success- object containing error-notes on failure
            print response[0], response[1]
            if response[0]:
                print "Update was successful"
                return redirect('/success')

            else:
                print "Update has errors"
                #Load error_notes returned from registration method into messages
                error_notes = response[1]
                for key, note in error_notes.items():
                    messages.error(request, note, extra_tags=key)

                return redirect('/account')

        else:
            #If the route recieves a non-POST request- assume something shady is going on- log the user out
            #this might be a little harsh if there are legitimate ways a user might accidentally send a GET request to /register
            print "Invalid request method"
            return redirect('/logout')

def delete(request, delete_id):
    print "/////////////////////////// Starting login_reg.views.py delete route"
    try:
        user = User.objects.get(id=delete_id)
        if user.id == request.session['login_id']:
            user.delete()
            return redirect('/logout')
        else:
            user.delete()

    except User.DoesNotExist:
        print "Cannot delete User- id does not match any records"

    return redirect('/success')

def logout(request):
    print "/////////////////////////// Starting login_reg.views.py logout route"
    try:
        request.session.clear()
    except KeyError:
        print "User already logged out"

    return redirect('/')

apps/login_reg/templates/login_reg/account.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'login_reg/css/style.css' %}">
    <title>Login Registration</title>
  </head>
  <body>
    <h1>Account</h1>
    <form class="form" action="{%url 'login_reg:update' %}" method="post">
      {% csrf_token %}
      <!-- I perfer this ugly inline error note loop format to one that looks prettier but takes up 5 lines -->
      <p class="error" >{% for message in messages %}{% if message.extra_tags == 'first_name' %}{{message}}{% endif %}{% endfor %}</p>
      <!-- I am using a 'text' rather than 'email' input to test backend validations-->
      <input type="text" name="first_name" placeholder="First Name" value="{{request.session.user_info.first_name}}" >

      <p class="error" >{% for message in messages %}{% if message.extra_tags == 'last_name' %}{{message}}{% endif %}{% endfor %}</p>
      <input type="text" name="last_name" placeholder="Last Name" value="{{request.session.user_info.last_name}}">

      <p class="error" >{% for message in messages %}{% if message.extra_tags == 'email' %}{{message}}{% endif %}{% endfor %}</p>
      <input type="text" name="email" placeholder="Email" value="{{request.session.user_info.email}}">

      <p class="error" >{% for message in messages %}{% if message.extra_tags == 'birthday' %}{{message}}{% endif %}{% endfor %}</p>
      <input type="date" name="birthday" placeholder="Birthday" value="{{request.session.user_info.birthday}}">

      <input class="submit" type="submit" name="submit" value="Update"> <a class="cancel" href="/success">Cancel</a>
    </form>
  </body>
</html>

apps/login_reg/templates/login_reg/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'login_reg/css/style.css' %}">

    <title>Login Registration</title>
  </head>
  <body>
    <h1>Login Registration</h1>
    <h3>Register</h3>
    <form class="form" action="{%url 'login_reg:register' %}" method="post">
      {% csrf_token %}
      <!-- I perfer this ugly error note loop format to one that looks prettier but takes up 5 lines -->
      <p class="error" >{% for message in messages %}{% if message.extra_tags == 'first_name' %}{{message}}{% endif %}{% endfor %}</p>
      <!-- I am using a 'text' rather than 'email' input to test backend validations-->
      <input type="text" name="first_name" placeholder="First Name" value="{% for message in messages %}{% if message.extra_tags == 'first_name_value' %}{{message}}{% endif %}{% endfor %}" >
      <p class="error" >{% for message in messages %}{% if message.extra_tags == 'last_name' %}{{message}}{% endif %}{% endfor %}</p>
      <input type="text" name="last_name" placeholder="Last Name" value="{% for message in messages %}{% if message.extra_tags == 'last_name_value' %}{{message}}{% endif %}{% endfor %}">
      <p class="error" >{% for message in messages %}{% if message.extra_tags == 'email' %}{{message}}{% endif %}{% endfor %}</p>
      <input type="text" name="email" placeholder="Email" value="{% for message in messages %}{% if message.extra_tags == 'email_value' %}{{message}}{% endif %}{% endfor %}">
      <p class="error" >{% for message in messages %}{% if message.extra_tags == 'birthday' %}{{message}}{% endif %}{% endfor %}</p>
      <input type="date" name="birthday" placeholder="Birthday" value="{% for message in messages %}{% if message.extra_tags == 'birthday_value' %}{{message}}{% endif %}{% endfor %}">
      <p class="guide" >Password must be at least 8 characters long with at least one capital and at least one number</p>
      <p class="error" >{% for message in messages %}{% if message.extra_tags == 'password' %}{{message}}{% endif %}{% endfor %}</p>
      <input type="password" name="password" placeholder="Password" value="">
      <p class="error" >{% for message in messages %}{% if message.extra_tags == 'c_password' %}{{message}}{% endif %}{% endfor %}</p>
      <input type="password" name="c_password" placeholder="Confirm Password" value="">
      <input class="submit" type="submit" name="submit" value="Register">
    </form>
    <h3>Login</h3>
    <form class="login_form" action="{%url 'login_reg:login' %}" method="post">
      {% csrf_token %}
      <!-- I am using a 'text' rather than 'email' input to test backend validations-->
      <p class="error" >{% for message in messages %}{% if message.extra_tags == 'login_email' %}{{message}}{% endif %}{% endfor %}</p>
      <input type="text" name="login_email" placeholder="Email" value="">
      <p class="error" >{% for message in messages %}{% if message.extra_tags == 'login_password' %}{{message}}{% endif %}{% endfor %}</p>
      <input type="password" name="login_password" placeholder="Password" value="">
      <input class="submit" type="submit" name="submit" value="Login">
    </form>
  </body>
</html>