BookReview/urls.py
from django.conf.urls import url, include


urlpatterns = [
    url(r'^books/', include('apps.book_review.urls', namespace='book_review')),
    url(r'^', include('apps.login_reg.urls', namespace='login_reg')),
]

apps/book_review/urls.py
from django.conf.urls import url, include
from . import views


app_name = "book_review"
urlpatterns = [
    #Home
    url(r'^$', views.index, name='index'),

    #Show 'new_form'
    url(r'^new$', views.new, name='new'),
    #POST process 'new_form'
    url(r'^create$', views.create, name='create'),

    #Show individual
    url(r'^(?P<id>[\d]{1,6})$', views.show, name="show"),

    #Show 'edit_form'
    url(r'^edit/(?P<id>[\d]{1,6})$', views.edit, name='edit'),
    #POST route to process 'edit_form'
    url(r'^update/(?P<id>[\d]{1,6})$', views.update, name="update"),

    #Delete route shows "are you sure" destroy form
    url(r'^delete/(?P<id>[\d]{1,6})$', views.delete, name="delete"),
    #Destroys book
    url(r'^destroy/(?P<id>[\d]{1,6})$', views.destroy, name="destroy"),
]

apps/login_reg/urls.py
from django.conf.urls import url
from . import views

app_name='login_reg'
urlpatterns = [
    #home route- displays registration and login forms
    url(r'^$', views.index, name='index'),

    #process registration form
    #sends to books_app index on success
    url(r'^register$', views.register, name='register'),

    #process login form
    #sends to books_app index on success
    url(r'^login$', views.login, name='login'),

    #display form for updating user info and security questions
    url(r'^account$', views.account, name='account'),

    url(r'^show/(?P<id>[\d]{1,})$', views.show, name='show'),
    #process update form
    #sends to success on success
    url(r'^update$', views.update, name='update'),

    #Logs user out
    #Sends to index
    url(r'^delete/(?P<delete_id>[\d]{1,})$', views.delete, name='delete'),

    #Logs user out
    #Sends to index
    url(r'^logout$', views.logout, name='logout'),
]

apps/book_review/models.py
from __future__ import unicode_literals
from django.db import models
from ..login_reg.models import User
import re, time

#regex object stores regex validations and error messages
#some regexs are duplicates so that field-names can be preserved,
#fields like email and login_email have idetical regex but errors need to be displayed in different places
regex = {
    'title' : (re.compile(r'^([\w ]{1,50})$'), "Title must be only letters or numbers and no more than 50 characters long"),
    'author_list' : (re.compile(r'^[a-zA-Z]+[a-zA-Z ]*$'), "Author name must not contain any numbers or symbols"),
    'author_name' : (re.compile(r'^[a-zA-Z]+[a-zA-Z ]*$'), "Author name must not contain any numbers or symbols"),
    #Rating error should only show if something has gone wrong with the HTML or somone is messing with the front-end
    #The input should only allow valid ratings
    'rating' : (re.compile(r'^[1-5]$'), "Invalid rating"),
}

class BookManager(models.Manager):
    #Checks for empty fields and Uses regex object to validate format.
    #first value in tuple is true or false- registration is valid
    #second value returns an error notes object if form has errors, or a Book info object if form is valid
    def validateFields(self, form_data):
        print "Starting book_review.models.py BookManager validateFields method"
        valid = True
        error_notes = {}
        #Check for empty fields
        for key, value in form_data.items():
            print "Checking for value in {} field".format(key)
            if len(value) == 0:
                print "//////////////////// Form Error- {} field is empty".format(key)
                valid = False
                error_notes[key] = "This field cannot be empty"

        #Check for valid field formats- if regex exists for field- validate
        for key, value in form_data.items():
            #Check to see if regex exists for field
            if key in regex:
                print "Checking format of {} field".format(key)
                if not regex[key][0].search(value):
                    print "//////////////////// Form Error- {} field is invalid format".format(key)
                    valid = False
                    #If invalid, and no error note has been set for this field- pull error matching error message from regex dictionary
                    #The error notes will contain the most basic note for each field.
                    if not key in error_notes:
                        error_notes[key] = regex[key][1]

        return (valid, error_notes)

    def createBook(self, form_data, user):
        print "Starting book_review.models.py BookManager createBook method"
        print "models form_data = ", form_data
        book_author = 'none'
        create_author = False
        valid = True
        #Check to see if new author was added
        if form_data['author_list'] != 'none' and len(form_data['author_name']) == 0:
            #if an author was choosen from the list- set author name to 'None' so it will not trigger validation errors
            #it will be ignored in later steps
            print "Author selected from existing list"
            form_data['author_name'] = 'none'
        elif form_data['author_list'] == 'none' and len(form_data['author_name']) > 0:
            print "New Author entered"
            #Set create_author to true so that we know to create a new author
            create_author = True
        else:
            "Both new Author and Author from list selected"
            valid = False

        response = self.validateFields(form_data)
        error_notes = response[1]
        if not response[0]:
            print "return 1"
            return (False, error_notes)
        #Additional method-specific validations
        if len(form_data['review']) > 200:
            valid = False
            if not 'review' in error_notes:
                #Review length should already be limited by the html input field- this serves as a double-check
                error_notes['review'] = "Review must be less than 200 characters"
        if valid == False:
            print "Form has errors"
            print "return 2"
            for error in error_notes.values():
                print error
            return (False, error_notes)

        #After form has been validated- check to see if new Author needs to be created
        if create_author:
            new_author = Author.objects.create(name=form_data['author_name'])
            book_author = new_author
        else:
            try:
                book_author = Author.objects.get(name=form_data['author_list'])
            except Author.DoesNotExist:
                #The author list options are generated from the DB so this error should not occur
                print "////////////////////////////////////////// Form Error- Author from author_list does not match any record in the DB- cannot create new title and review"
                error_notes['author_list'] = 'We are sorry but the author you selected cannot be found in our records. Please try selecting a different author or create a new author below'
                print "return 3"
                return (False, error_notes)
        print "//////////////////////////////////Form is Vald- Creating Book"
        print form_data
        new_book = Book.objects.create(title=form_data['title'], author=book_author)

        #create a new review linked to the book_review
        new_review = Review.objects.create(content=form_data['review'], rating=form_data['rating'], user=user, book=new_book)
        print "return 4"
        return (True, new_book.id)

    def createReview(self, content, book, user):
        pass

    def updateBook(self, form_data, Book_id):
        print "Starting book_review.models.py BookManager update method"
        #Uses validateFields method to check for basic field validations- if successful,
        #Updates Book info if form is valid
        response = Book.objects.validateFields(form_data)
        valid = True
        error_notes = response[1]
        #Check if basic validation returned false
        if not response[0]:
            return (False, error_notes)
        #Additional method-specific validations
        if len(form_data['review']) > 200:
            valid = False
            if not 'review' in error_notes:
                #Review length should already be limited by the html input field- this serves as a double-check
                error_notes['review'] = "Review must be less than 200 characters"

        if valid == False:
            print "Form has errors"
            return (False, error_notes)
        #After form has been validated- add updates
        print "//////////////////////////////////Form is Vald- Updating Book"
        Book = Book.objects.get(id=Book_id)
        Book.name = form_data['name']
        Book.review = form_data['review']
        Book.price = form_data['price']
        Book.save()
        #Returning the Book id is not nessesary here but it maintains consistency
        #in the way the methods process and return data
        return (True, Book.id)

    def destroyBook(self, Book_id):
        try:
            delete_Book = Book.objects.get(id=Book_id)
        except Book.DoesNotExist:
            print "Book matching that id not found in DB"
            return False

        delete_Book.delete()
        return True

class Author(models.Model):
    name = models.CharField(max_length=55)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Book(models.Model):
    title = models.CharField(max_length=55)
    author = models.ForeignKey(Author)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = BookManager()

class Review(models.Model):
    content = models.TextField(max_length=300)
    rating = models.PositiveIntegerField()
    user = models.ForeignKey(User)
    book = models.ForeignKey(Book)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    objects = BookManager()

apps/book_review/views.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.contrib import messages
from ..login_reg.models import User
from models import Book, Author, Review

def index(request):
    print "///////////////////////////////////Starting book_review Index route"
    books = Book.objects.all()
    reviews = Review.objects.all()
    context = {
        'books' : books,
        'reviews' : reviews,
    }
    return render(request, 'book_review/index.html', context)

def new(request):
    print "///////////////////////////////////Starting book_review New route"
    authors = Author.objects.all()
    context = {
        'authors' : authors
    }
    return render(request, 'book_review/new.html', context)

def create(request):
    print "///////////////////////////////////Starting book_review Create route"
    try:
        user = User.objects.get(id=request.session['login_id'])
    except:
        print "User is not logged in"
        return redirect(reverse('login_reg:logout'))
    if request.method == 'POST':
        print "Post method"
        form_data = {
            'title' : request.POST['title'],
            'author_list' : request.POST['author_list'],
            'author_name' : request.POST['author_name'],
            'review' : request.POST['review'],
            'rating' : request.POST['rating'],
        }
        print "views form_data = ", form_data

        response = Book.objects.createBook(form_data, user)
        if response[0]:
            print "Create is successful"
            book_id = str(response[1])
            return redirect(reverse('book_review:index'))
            #return redirect( reverse('book_review:show', kwargs={'id':book_id}) )

        else:
            print "new_form has errors"
            #Load error_notes returned from registration method into messages
            error_notes = response[1]
            for key, note in error_notes.items():
                messages.error(request, note, extra_tags=key)

            #Preserve any values that do not have error messages and pass them back to the registration form
            for key, value in form_data.items():
                if key not in error_notes:
                    messages.info(request, value, extra_tags=key + "_value")
            print "Sending back to new.html"
            print messages
            return redirect(reverse('book_review:new'))
    else:
        print "Invalid request type"
    return redirect(reverse('book_review:index'))

def show(request, id):
    print "///////////////////////////////////Starting book_review Show route"
    try:
        user = User.objects.get(id=request.session['login_id'])
    except:
        print "User is not logged in"
        return redirect(reverse('login_reg:logout'))
    try:
        book = Book.objects.get(id=id)
    except Book.DoesNotExist:
        print "No book matches the id", id
        return redirect(reverse('book_review:index'))

    reviews = Review.objects.filter(book=book)
    context = {
        'id' : book.id,
        'title' : book.title,
        'author' : book.author.name,
        'reviews' : reviews,
    }
    return render(request, 'book_review/show.html', context)

def edit(request, id):
    print "///////////////////////////////////Starting book_review Edit route"
    try:
        book = Book.objects.get(id=id)
    except Book.DoesNotExist:
        print "No book matches the id", id
        return redirect(reverse('book_review:index'))

    context = {
        'id' : book.id,
        'name' : book.name,
        'description' : book.description,
        'price' : book.price,
    }

    return render(request, 'book_review/edit.html', context)

def update(request, id):
    print "///////////////////////////////////Starting book_review Update route"
    if request.method == 'POST':
        print "Post method id=", id
        form_data = {
            'name' : request.POST['name'],
            'description' : request.POST['description'],
            'price' : request.POST['price'],
        }
        print "views form_data = ", form_data
        response = Book.objects.updateBook(form_data, id)
        if response[0]:
            print "Update is successful"
            book_id = str(response[1])
            return redirect( reverse('book_review:show', kwargs={'id':book_id}) )

        else:
            print "edit_form has errors"
            #Load error_notes returned from registration method into messages
            error_notes = response[1]
            for key, note in error_notes.items():
                messages.error(request, note, extra_tags=key)

            #Preserve any values that do not have error messages and pass them back to the registration form
            for key, value in form_data.items():
                if key not in error_notes:
                    messages.info(request, value, extra_tags=key + "_value")
            print "Sending back to edit.html"
            return redirect(reverse('book_review:edit', kwargs={'id':id}))
    else:
        print "Invalid request type"
    return redirect(reverse('book_review:index'))

def delete(request, id):
    print "///////////////////////////////////Starting book_review Delete route"
    try:
        book = Book.objects.get(id=id)
        print "Book with id", book.id, "found"
    except Book.DoesNotExist:
        print "No book matches the id", id
        return redirect(reverse('book_review:index'))

    context = {
        'id' : book.id,
        'name' : book.name,
        'description' : book.description,
        'price' : book.price,
    }

    return render(request, 'book_review/destroy.html', context)

def destroy(request, id):
    print "///////////////////////////////////Starting book_review Destroy route"
    if request.method == 'POST':
        response = Book.objects.destroyBook(id)
        if response:
            print "Book has been deleted"
        else:
            print "Error- no book matching that id found in DB"
        print "Post method"

    else:
        print "Invalid request type"
    return redirect(reverse('book_review:index'))

apps/book_review/templates/book_review/destroy.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>SemiRestful</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'book_review/css/style.css' %}">
  </head>
  <body>
    <h3>Review id: {{id}}</h3>
    
    <h3 class="error">Are you sure you want to permanently delete this review?</h3>
    <form class="delete" action="{% url 'book_review:destroy' id %}" method="post">
      {% csrf_token %}
      <input type="submit" name="submit" value="Delete Review">
    </form>
    <a class="button" href="{% url 'book_review:index' %}">Cancel</a>
  </body>
</html>

apps/book_review/templates/book_review/edit.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>SemiRestful</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'book_review/css/style.css' %}">
  </head>
  <body>
    <h1>Edit Product Info</h1>
    <h3>Product id: {{id}}</h3>
    <!-- <form class="edit_form" action="/{{id}}" method="post"> -->
    <form class="edit_form" action="{% url 'book_review:update' id=id %}" method="post">
      {% csrf_token %}
      <p class="error" >{% for message in messages %}{% if message.extra_tags == 'name' %}{{message}}{% endif %}{% endfor %}</p>
      <input type="text" name="name" placeholder="Name" value="{{name}}">
      <input type="text" name="description" placeholder="Description" value="{{description}}">
      <input type="number" name="price" min="0" max="100000" step="0.01" placeholder="Price" value="{{price}}">
      <input type="submit" name="submit" value="Submit">
    </form>
    <a class="button" href="{% url 'book_review:index' %}">Cancel</a>
  </body>
</html>

apps/book_review/templates/book_review/index.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Book Review</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'book_review/css/style.css' %}">
  </head>
  <body>
    <h1>Book Reviews</h1>
    <h2>Welcome UserName</h2>
    <a href="{% url 'login_reg:logout' %}">logout</a>
    <div class="recent_reviews">
      <h3>Recent Book Reviews</h3>
      {% for review in reviews %}
        <div class="review">
          <a class="title_link" href="{% url 'book_review:show' id=review.id %}"><h3><strong>{{review.book.title}}</strong></h3></a>
          <p>Review: {{review.content}}</p>
          <a href="{% url 'book_review:edit' id=review.id %}">Edit</a>
          <a href="{% url 'book_review:delete' id=review.id %}">Delete</a>
        </div>
      {% endfor %}
    </div>

    <div class="all_books">
      <h3>Other Books with Reviews</h3>
      {% for book in books %}
        <div class="book">
          <a class="title_link" href="{% url 'book_review:show' id=book.id %}"><h3><strong>{{book.title}}</strong></h3></a>
        </div>
      {% endfor %}
    </div>
    <a class="button" href="{% url 'book_review:new' %}">Add New</a>
  </body>
</html>

apps/book_review/templates/book_review/new.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>SemiRestful</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'book_review/css/style.css' %}">
  </head>
  <body>
    <h1>Add a New Book Title or a New Review</h1>
    <form class="new_form" action="{% url 'book_review:create' %}" method="post">
      {% csrf_token %}
      <p class="error" >{% for message in messages %}{% if message.extra_tags == 'title' %}{{message}}{% endif %}{% endfor %}</p>
      <input type="text" name="title" placeholder="Book Title" value="{% for message in messages %}{% if message.extra_tags == 'title_value' %}{{message}}{% endif %}{% endfor %}">

      <label for="author_list">Choose from the list</label>
      <select class="author_select" name="author_list">
          <option value="none">None</option>
        {% for author in authors %}
          <!-- The app does not allow two authors to share the same name. -->
          <option value="{{author.name}}">{{author.name}}</option>
        {% endfor %}
      </select>

      <p class="error" >{% for message in messages %}{% if message.extra_tags == 'author_name' %}{{message}}{% endif %}{% endfor %}</p>
      <input type="text" name="author_name" placeholder="Add a new Author" value="{% for message in messages %}{% if message.extra_tags == 'author_name_value' %}{{message}}{% endif %}{% endfor %}">

      <p class="error" >{% for message in messages %}{% if message.extra_tags == 'review' %}{{message}}{% endif %}{% endfor %}</p>
      <textarea name="review" placeholder="Review" maxlength="200">{% for message in messages %}{% if message.extra_tags == 'review_value' %}{{message}}{% endif %}{% endfor %}</textarea>
      <label for="rating">Rating</label>
      <p class="error" >{% for message in messages %}{% if message.extra_tags == 'rating' %}{{message}}{% endif %}{% endfor %}</p>
      <input type="number" name="rating" min="1" max="5" value="{% for message in messages %}{% if message.extra_tags == 'rating_value' %}{{message}}{% endif %}{% endfor %}">

      <input type="submit" name="submit" value="Add Book and Review">
    </form>

    <a class="button" href="{% url 'book_review:index' %}">Cancel</a>
  </body>
</html>

apps/book_review/templates/book_review/show.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>SemiRestful</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'book_review/css/style.css' %}">
  </head>
  <body>
    <h3>{{title}}</h3>
    <p>Author: {{author}}</p>
    <h3>Reviews</h3>
    {% for review in reviews %}
      <p><a href="{% url 'login_reg:show' id=review.user.id %}">{{review.user.first_name}}</a> says {{review.content}}</p>
      {% if review.user.id == request.session.login_id %}
        <a href="{% url 'book_review:delete' id=id %}">Delete</a>
      {% endif %}
    {% endfor %}

    <a class="button" href="{% url 'book_review:index' %}">View All</a>
  </body>
</html>